name: generate-builds
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-windows:
    runs-on: ${{ (vars.WINDOWS_RUNNER && fromJSON(vars.WINDOWS_RUNNER)) || 'windows-latest' }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-ccache
    - name: Install dependencies
      run: |
        choco install ninja
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: dcvz/ccache-action@27b9f33213c0079872f064f6b6ba0233dfa16ba2
      with:
        key: ${{ runner.os }}-ccache
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Setup 7-Zip
      run: |
        "C:\Program Files\7-Zip" >> $env:GITHUB_PATH
    - name: Build SoH
      run: |
        set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build-windows --target OTRGui --config Release --parallel 10
        cmake --build build-windows --config Release --parallel 10
        cd build-windows
        cpack -G ZIP
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-windows-${{ matrix.runs-on }}
        path: _packages/*.zip
